# FILE: backend/konnaxion/moderation/migrations/0001_initial.py
# Generated by Django 5.1.9 on 2025-11-24 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the event occurred.')),
                ('actor', models.CharField(blank=True, help_text='Denormalized actor label exposed in the API.', max_length=255)),
                ('action', models.CharField(help_text="Logical action identifier, e.g. 'UPDATE_TOPIC'.", max_length=128)),
                ('target', models.CharField(blank=True, help_text='Human-readable target used in the admin UI.', max_length=255)),
                ('entity', models.CharField(blank=True, help_text="Machine-oriented entity type, e.g. 'topic', 'argument', 'user'.", max_length=64)),
                ('entity_id', models.CharField(blank=True, help_text='Primary key of the entity in the source system, stored as text.', max_length=64)),
                ('entity_object_id', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warn', 'Warning'), ('error', 'Error')], db_index=True, default='ok', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Source IP address, if available.', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Free-form JSON payload with extra context for the event.')),
                ('actor_user', models.ForeignKey(blank=True, help_text='Optional link to the user that triggered the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('entity_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ('-ts',),
            },
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.CharField(blank=True, help_text='Primary key of the moderated object, stored as text.', max_length=64)),
                ('target_type', models.CharField(choices=[('topic', 'Topic'), ('post', 'Post / argument'), ('user', 'User'), ('other', 'Other')], default='post', help_text='UI-level category of the moderated target (topic, post, user, …).', max_length=16)),
                ('target_id', models.CharField(blank=True, help_text='External identifier exposed to frontends (argumentId, topicId, userId, …).', max_length=64)),
                ('context_title', models.CharField(blank=True, help_text='Debate / consultation context, e.g. topic title.', max_length=255)),
                ('content_preview', models.TextField(blank=True, help_text='Short snapshot of the offending content for quick review.')),
                ('author_name', models.CharField(blank=True, help_text='Cached author label for admin views.', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], db_index=True, default='Pending', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=8)),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Denormalized number of merged user reports for this case.')),
                ('source', models.CharField(blank=True, help_text="Originating app or module (e.g. 'ethikos', 'keenkonnect').", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases_authored', to=settings.AUTH_USER_MODEL)),
                ('last_moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases_moderated', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Moderation case',
                'verbose_name_plural': 'Moderation cases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve content'), ('remove', 'Remove content'), ('escalate', 'Escalate / flag'), ('ignore', 'Ignore / keep pending')], max_length=16)),
                ('notes', models.TextField(blank=True, help_text='Optional internal notes from the moderator.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_entry', models.ForeignKey(blank=True, help_text='Optional link to the audit log entry for this decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='moderation.auditlogentry')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.moderationcase')),
            ],
            options={
                'verbose_name': 'Moderation action',
                'verbose_name_plural': 'Moderation actions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, help_text='Cached reporter label for admin views.', max_length=255)),
                ('type', models.CharField(choices=[('Spam', 'Spam'), ('Harassment', 'Harassment'), ('Misinformation', 'Misinformation'), ('Other', 'Other')], default='Spam', help_text='Primary moderation reason label.', max_length=32)),
                ('message', models.TextField(blank=True, help_text='Optional free-text notes supplied by the reporter.')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON payload with source-specific details.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Source IP address of the reporter, if tracked.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='moderation.moderationcase')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation report',
                'verbose_name_plural': 'Moderation reports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['ts'], name='moderation__ts_083a34_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['severity'], name='moderation__severit_95739a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['status'], name='moderation__status_8f4da0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['entity', 'entity_id'], name='moderation__entity_76cedd_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', 'severity'], name='moderation__status_3af731_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['target_type', 'target_id'], name='moderation__target__2376b2_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['created_at'], name='moderation__created_b76f35_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationreport',
            index=models.Index(fields=['type'], name='moderation__type_10cf49_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationreport',
            index=models.Index(fields=['created_at'], name='moderation__created_ae337c_idx'),
        ),
    ]
