# Generated by Django 5.1.9 on 2025-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlogentry',
            name='entity_content_type',
        ),
        migrations.RemoveField(
            model_name='auditlogentry',
            name='entity_object_id',
        ),
        migrations.RemoveField(
            model_name='moderationcase',
            name='author',
        ),
        migrations.RemoveField(
            model_name='moderationcase',
            name='last_moderated_by',
        ),
        migrations.RemoveField(
            model_name='moderationcase',
            name='source',
        ),
        migrations.AddField(
            model_name='moderationcase',
            name='author_id',
            field=models.CharField(blank=True, help_text='External identifier of the content author.', max_length=64),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='author_name',
            field=models.CharField(blank=True, help_text='Cached name of the content author.', max_length=255),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='content_preview',
            field=models.TextField(blank=True, help_text='Short excerpt of the offending content, for quick triage.'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='context_title',
            field=models.CharField(blank=True, help_text='Title or short label providing context in the queue.', max_length=255),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='last_action_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last moderation action.', null=True),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='report_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of individual reports associated with this case.'),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=16),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='target_id',
            field=models.CharField(blank=True, help_text='External target identifier used by the frontend.', max_length=64),
        ),
        migrations.AlterField(
            model_name='moderationcase',
            name='target_type',
            field=models.CharField(choices=[('topic', 'Topic'), ('post', 'Post / argument'), ('user', 'User'), ('other', 'Other')], default='post', help_text='High-level target bucket for the queue UI.', max_length=16),
        ),
    ]
