# FILE: backend/konnaxion/kollective_intelligence/migrations/0001_initial.py
# Generated by Django 5.1.9 on 2025-06-26 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialitySetting',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level', models.CharField(choices=[('public', 'Public'), ('pseudonym', 'Pseudonym'), ('anonymous', 'Anonymous')], default='public', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContextAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('field', models.CharField(max_length=64)),
                ('input_metadata', models.JSONField()),
                ('adjustments_applied', models.JSONField()),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=40)),
                ('context_type', models.CharField(max_length=40)),
                ('mapping_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEthicsScore',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ethical_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='VoteModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('parameters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergingExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateField(default=django.utils.timezone.now)),
                ('score_delta', models.DecimalField(decimal_places=3, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emerging_expert_flags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_name', models.CharField(max_length=64)),
                ('weight_value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'unique_together': {('weight_name', 'field')},
            },
        ),
        migrations.CreateModel(
            name='UserExpertiseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('weighted_score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='kollective_intelligence.expertisecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(decimal_places=3, max_digits=7)),
                ('new_value', models.DecimalField(decimal_places=3, max_digits=7)),
                ('change_reason', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merit_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kollective_intelligence.userexpertisescore')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.PositiveBigIntegerField()),
                ('raw_value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weighted_value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.PositiveBigIntegerField()),
                ('sum_weighted_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('vote_count', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('target_type', 'target_id')},
            },
        ),
        migrations.AddIndex(
            model_name='userexpertisescore',
            index=models.Index(fields=['category', '-weighted_score'], name='kollective__categor_c5228d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userexpertisescore',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'target_type', 'target_id')},
        ),
    ]
