# Generated by Django 5.1.9 on 2026-04-24 00:24

from django.contrib.postgres.indexes import GistIndex
import django.db.models.deletion
import konnaxion.ekoh.models.taxonomy
from django.db import migrations, models

from konnaxion.worlds.migration_context import get_target_ekoh_schema


def set_ekoh_schema_scope(apps, schema_editor):
    schema = get_target_ekoh_schema()
    quoted = schema_editor.connection.ops.quote_name(schema)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SET LOCAL search_path TO {quoted}, public")


class Migration(migrations.Migration):

    dependencies = [
        ("ekoh", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_ekoh_schema_scope, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="expertisecategory",
            name="idx_cat_path",
        ),
        migrations.AlterField(
            model_name="expertisecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="ekoh.expertisecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expertisecategory",
            name="path",
            field=konnaxion.ekoh.models.taxonomy.LTreeField(),
        ),
        migrations.AddIndex(
            model_name="expertisecategory",
            index=GistIndex(fields=["path"], name="idx_cat_path"),
        ),
    ]
