# FILE: backend/konnaxion/ethikos/migrations/0002_initial.py
# Generated by Django 5.1.9 on 2025-06-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ethikos', '0001_initial'),
        ('kollective_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethikostopic',
            name='expertise_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kollective_intelligence.expertisecategory'),
        ),
        migrations.AddField(
            model_name='ethikosstance',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stances', to='ethikos.ethikostopic'),
        ),
        migrations.AddField(
            model_name='ethikosargument',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='ethikos.ethikostopic'),
        ),
        migrations.AddIndex(
            model_name='ethikosstance',
            index=models.Index(fields=['topic'], name='ethikos_eth_topic_i_791d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='ethikosstance',
            index=models.Index(fields=['user'], name='ethikos_eth_user_id_fe6937_idx'),
        ),
        migrations.AddConstraint(
            model_name='ethikosstance',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', -3), ('value__lte', 3)), name='stance_value_between_-3_and_3'),
        ),
        migrations.AlterUniqueTogether(
            name='ethikosstance',
            unique_together={('user', 'topic')},
        ),
        migrations.AddIndex(
            model_name='ethikosargument',
            index=models.Index(fields=['topic'], name='ethikos_eth_topic_i_53cecf_idx'),
        ),
        migrations.AddIndex(
            model_name='ethikosargument',
            index=models.Index(fields=['user'], name='ethikos_eth_user_id_0f0683_idx'),
        ),
    ]
