# Generated by Django 5.1.9 on 2026-04-29 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethikos', '0003_kintsugi_wave1_korum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoScenarioImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_key', models.CharField(db_index=True, help_text='Stable key from the demo scenario JSON, e.g. public_square_demo.', max_length=120)),
                ('object_type', models.CharField(choices=[('user', 'User'), ('category', 'Ethikos Category'), ('topic', 'Ethikos Topic'), ('stance', 'Ethikos Stance'), ('argument', 'Ethikos Argument'), ('consultation', 'Consultation'), ('consultation_vote', 'Consultation Vote'), ('consultation_result', 'Consultation Result'), ('impact_item', 'Impact Item')], db_index=True, help_text='Type of imported object, e.g. topic, stance, consultation_vote.', max_length=120)),
                ('object_id', models.PositiveBigIntegerField(db_index=True, help_text='Primary key of the imported object.')),
                ('object_label', models.CharField(blank=True, help_text='Human-readable label for debugging and reset reports.', max_length=255)),
                ('source_key', models.CharField(blank=True, db_index=True, help_text='Optional JSON object key, e.g. public_square or maya_argument_1.', max_length=120)),
                ('imported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('imported_by', models.ForeignKey(blank=True, help_text='Admin user who imported the demo scenario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethikos_demo_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo scenario import',
                'verbose_name_plural': 'Demo scenario imports',
                'ordering': ['-imported_at', 'scenario_key', 'object_type'],
                'indexes': [models.Index(fields=['scenario_key', 'object_type'], name='eth_demo_scen_type_idx'), models.Index(fields=['object_type', 'object_id'], name='eth_demo_obj_idx'), models.Index(fields=['scenario_key', 'source_key'], name='eth_demo_source_idx'), models.Index(fields=['scenario_key', 'imported_at'], name='eth_demo_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('scenario_key', 'object_type', 'object_id'), name='uniq_eth_demo_import_obj')],
            },
        ),
    ]
