# FILE: backend/konnaxion/kreative/migrations/0001_initial.py
# Generated by Django 5.1.9 on 2025-06-26 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KreativeArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media_file', models.FileField(upload_to='kreative/artworks/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='image', max_length=10)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('style', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreative.gallery')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreative.kreativeartwork')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('gallery', 'artwork')},
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='artworks',
            field=models.ManyToManyField(related_name='galleries', through='kreative.GalleryArtwork', to='kreative.kreativeartwork'),
        ),
        migrations.CreateModel(
            name='CollabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('session_type', models.CharField(choices=[('painting', 'Painting'), ('music', 'Music'), ('mixed', 'Mixed Media')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_sessions_hosted', to=settings.AUTH_USER_MODEL)),
                ('final_artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_in_sessions', to='kreative.kreativeartwork')),
            ],
            options={
                'verbose_name': 'Collaboration Session',
                'verbose_name_plural': 'Collaboration Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreative.kreativeartwork')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kreative.tag')),
            ],
            options={
                'unique_together': {('artwork', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='kreativeartwork',
            name='tags',
            field=models.ManyToManyField(blank=True, through='kreative.ArtworkTag', to='kreative.tag'),
        ),
        migrations.CreateModel(
            name='TraditionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('region', models.CharField(max_length=120)),
                ('media_file', models.FileField(upload_to='kreative/traditions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradition_entries_approved', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tradition Entry',
                'verbose_name_plural': 'Tradition Entries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
