# FILE: backend/konnaxion/kreative/migrations/0002_archivedocument_culturalpartner_digitalarchive_and_more.py
# Generated by Django 5.1.9 on 2025-11-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Archive Document',
                'verbose_name_plural': 'Archive Documents',
            },
        ),
        migrations.CreateModel(
            name='CulturalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=64)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Cultural Partner',
                'verbose_name_plural': 'Cultural Partners',
            },
        ),
        migrations.CreateModel(
            name='DigitalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Digital Archive',
                'verbose_name_plural': 'Digital Archives',
            },
        ),
        migrations.CreateModel(
            name='VirtualExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Virtual Exhibition',
                'verbose_name_plural': 'Virtual Exhibitions',
            },
        ),
        migrations.CreateModel(
            name='AICatalogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('classification', models.CharField(blank=True, max_length=120)),
                ('archive_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_entries', to='kreative.archivedocument')),
            ],
            options={
                'verbose_name': 'AI Catalogue Entry',
                'verbose_name_plural': 'AI Catalogue Entries',
            },
        ),
        migrations.AddField(
            model_name='archivedocument',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kreative.digitalarchive'),
        ),
    ]
