# Generated by Django 5.1.9 on 2025-12-01 22:15

import konnaxion.kreative.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreative', '0002_archivedocument_culturalpartner_digitalarchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kreativeartwork',
            name='media_file',
            field=models.FileField(upload_to=konnaxion.kreative.models.kreative_artwork_upload_to),
        ),
        migrations.AlterField(
            model_name='traditionentry',
            name='media_file',
            field=models.FileField(upload_to=konnaxion.kreative.models.tradition_media_upload_to),
        ),
    ]
