from __future__ import annotations

import hashlib
from collections import defaultdict, deque
from contextlib import contextmanager

from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import connection, transaction
from django.db.migrations.executor import MigrationExecutor

from ..db import validate_schema_name
from ..migration_context import override_ekoh_migration_schema

CANARY_TABLE = "kx_world_canary"
SCHEMA_CONTRACT_VERSION = "kx-world-schema/v1"

DEFAULT_DOMAIN_APPS = (
    "ethikos",
    "keenkonnect",
    "konnected",
    "kreative",
    "kollective_intelligence",
    "teambuilder",
    "moderation",
    "trust",
)
DEFAULT_EKOH_APPS = ("ekoh", "smart_vote")


def _q(identifier: str) -> str:
    return connection.ops.quote_name(validate_schema_name(identifier))


def _control_schema() -> str:
    return validate_schema_name(getattr(settings, "KONNAXION_CONTROL_SCHEMA", "public"))


def _set_search_path(*schemas: str) -> None:
    path = ", ".join(_q(schema) for schema in schemas)
    with connection.cursor() as cursor:
        cursor.execute(f"SET LOCAL search_path TO {path}")


def schema_exists(schema: str) -> bool:
    validate_schema_name(schema)
    with connection.cursor() as cursor:
        cursor.execute("SELECT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = %s)", [schema])
        return bool(cursor.fetchone()[0])


def create_schema(schema: str) -> None:
    with connection.cursor() as cursor:
        cursor.execute(f"CREATE SCHEMA IF NOT EXISTS {_q(schema)}")


def drop_schema(schema: str) -> None:
    with connection.cursor() as cursor:
        cursor.execute(f"DROP SCHEMA IF EXISTS {_q(schema)} CASCADE")


def _ensure_local_migration_recorder(schema: str) -> None:
    control = _control_schema()
    q_schema = _q(schema)
    q_control = _q(control)
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT to_regclass(%s)",
            [f"{control}.django_migrations"],
        )
        source_exists = cursor.fetchone()[0] is not None
        if source_exists:
            cursor.execute(
                f"CREATE TABLE IF NOT EXISTS {q_schema}.django_migrations "
                f"(LIKE {q_control}.django_migrations INCLUDING ALL)"
            )
        else:
            cursor.execute(
                f"CREATE TABLE IF NOT EXISTS {q_schema}.django_migrations ("
                "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "app varchar(255) NOT NULL, name varchar(255) NOT NULL, "
                "applied timestamp with time zone NOT NULL)"
            )


def _seed_dependency_migration_records(schema: str, target_apps: tuple[str, ...]) -> None:
    control = _control_schema()
    q_schema = _q(schema)
    q_control = _q(control)
    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [f"{control}.django_migrations"])
        if cursor.fetchone()[0] is None:
            return
        cursor.execute(
            f"INSERT INTO {q_schema}.django_migrations (app, name, applied) "
            f"SELECT app, name, applied FROM {q_control}.django_migrations "
            "WHERE NOT (app = ANY(%s)) "
            "ON CONFLICT DO NOTHING",
            [list(target_apps)],
        )


def _latest_targets(executor: MigrationExecutor, app_labels: tuple[str, ...]):
    targets = []
    for label in app_labels:
        leaves = executor.loader.graph.leaf_nodes(label)
        targets.extend(leaves)
    return targets


@contextmanager
def _migration_scope(*schemas: str, ekoh_schema: str | None = None):
    with transaction.atomic():
        _set_search_path(*schemas)
        if ekoh_schema:
            with override_ekoh_migration_schema(ekoh_schema):
                yield
        else:
            yield


def migrate_app_group_into_schema(
    *,
    primary_schema: str,
    fallback_schemas: tuple[str, ...],
    app_labels: tuple[str, ...],
    ekoh_schema_override: str | None = None,
) -> str:
    """Replay one Django migration group into an isolated schema.

    A schema-local django_migrations ledger is created. Migrations belonging to
    non-target apps are copied from the control ledger as dependency markers,
    while target app migrations are replayed physically in this schema.
    """
    create_schema(primary_schema)
    schemas = (primary_schema, *fallback_schemas)
    with _migration_scope(*schemas, ekoh_schema=ekoh_schema_override):
        _ensure_local_migration_recorder(primary_schema)
        _seed_dependency_migration_records(primary_schema, app_labels)
        executor = MigrationExecutor(connection)
        targets = _latest_targets(executor, app_labels)
        if targets:
            executor.migrate(targets)
    return migration_fingerprint(primary_schema, app_labels=app_labels)


def _migration_rows_fingerprint(rows) -> str:
    payload = "\n".join(f"{app}:{name}" for app, name in sorted(rows))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def migration_fingerprint(schema: str, *, app_labels: tuple[str, ...] | None = None) -> str:
    validate_schema_name(schema)
    q_schema = _q(schema)
    sql = f"SELECT app, name FROM {q_schema}.django_migrations"
    params: list[object] = []
    if app_labels:
        sql += " WHERE app = ANY(%s)"
        params.append(list(app_labels))
    sql += " ORDER BY app, name"
    with connection.cursor() as cursor:
        cursor.execute(sql, params)
        rows = cursor.fetchall()
    return _migration_rows_fingerprint(rows)


def expected_migration_fingerprint(app_labels: tuple[str, ...]) -> str:
    """Fingerprint the effective migration graph shipped by this code build."""
    executor = MigrationExecutor(connection)
    labels = set(app_labels)
    rows = [
        (app_label, name)
        for app_label, name in executor.loader.graph.nodes
        if app_label in labels
    ]
    return _migration_rows_fingerprint(rows)


def _required_model_tables(app_labels: tuple[str, ...]) -> set[str]:
    labels = set(app_labels)
    tables: set[str] = set()
    for model in django_apps.get_models(include_auto_created=True):
        if model._meta.app_label not in labels:
            continue
        if model._meta.proxy or not model._meta.managed:
            continue
        table = str(model._meta.db_table).strip('"')
        if "." in table:
            table = table.rsplit(".", 1)[-1].strip('"')
        tables.add(table)
    return tables


def missing_required_tables(schema: str, app_labels: tuple[str, ...]) -> list[str]:
    required = _required_model_tables(app_labels)
    if not required:
        return []
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = %s AND table_name = ANY(%s)",
            [schema, list(required)],
        )
        present = {row[0] for row in cursor.fetchall()}
    return sorted(required - present)


def foreign_key_targets(schema: str) -> list[dict[str, str]]:
    """Return physical FK targets for tables owned by one schema."""
    validate_schema_name(schema)
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT child.relname, parent_ns.nspname, parent.relname, con.conname
            FROM pg_constraint con
            JOIN pg_class child ON child.oid = con.conrelid
            JOIN pg_namespace child_ns ON child_ns.oid = child.relnamespace
            JOIN pg_class parent ON parent.oid = con.confrelid
            JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
            WHERE con.contype = 'f' AND child_ns.nspname = %s
            ORDER BY child.relname, con.conname
            """,
            [schema],
        )
        return [
            {
                "child_table": child,
                "parent_schema": parent_schema,
                "parent_table": parent,
                "constraint": constraint,
            }
            for child, parent_schema, parent, constraint in cursor.fetchall()
        ]


def fk_isolation_violations(
    *, domain_schema: str, ekoh_schema: str, domain_apps: tuple[str, ...], ekoh_apps: tuple[str, ...]
) -> list[dict[str, str]]:
    """Detect cross-World and public-fallback FK contamination."""
    control = _control_schema()
    allowed_schemas = {domain_schema, ekoh_schema, control}
    world_tables = _required_model_tables(domain_apps) | _required_model_tables(ekoh_apps)
    violations: list[dict[str, str]] = []
    for child_schema in (domain_schema, ekoh_schema):
        for row in foreign_key_targets(child_schema):
            parent_schema = row["parent_schema"]
            parent_table = row["parent_table"]
            reason = None
            if parent_schema not in allowed_schemas:
                reason = "foreign key targets a schema outside this WorldRelease"
            elif parent_schema == control and parent_table in world_tables:
                reason = "World-owned foreign key fell back to the control/public schema"
            if reason:
                violations.append({"child_schema": child_schema, **row, "reason": reason})
    return violations


def write_canary(*, schema: str, world_id: int, release_id: int, schema_kind: str) -> None:
    q_schema = _q(schema)
    with connection.cursor() as cursor:
        cursor.execute(
            f"CREATE TABLE IF NOT EXISTS {q_schema}.{CANARY_TABLE} ("
            "world_id bigint NOT NULL, release_id bigint NOT NULL, "
            "schema_kind varchar(16) NOT NULL, contract_version varchar(64) NOT NULL)"
        )
        cursor.execute(f"TRUNCATE TABLE {q_schema}.{CANARY_TABLE}")
        cursor.execute(
            f"INSERT INTO {q_schema}.{CANARY_TABLE} "
            "(world_id, release_id, schema_kind, contract_version) VALUES (%s, %s, %s, %s)",
            [world_id, release_id, schema_kind, SCHEMA_CONTRACT_VERSION],
        )


def read_canary(schema: str) -> dict | None:
    q_schema = _q(schema)
    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [f"{schema}.{CANARY_TABLE}"])
        if cursor.fetchone()[0] is None:
            return None
        cursor.execute(
            f"SELECT world_id, release_id, schema_kind, contract_version "
            f"FROM {q_schema}.{CANARY_TABLE} LIMIT 1"
        )
        row = cursor.fetchone()
    if not row:
        return None
    return {
        "world_id": row[0],
        "release_id": row[1],
        "schema_kind": row[2],
        "contract_version": row[3],
    }


def provision_release_schemas(release) -> tuple[str, str]:
    domain_apps = tuple(getattr(settings, "KONNAXION_WORLD_DOMAIN_APPS", DEFAULT_DOMAIN_APPS))
    ekoh_apps = tuple(getattr(settings, "KONNAXION_WORLD_EKOH_APPS", DEFAULT_EKOH_APPS))
    control = _control_schema()

    domain_fp = migrate_app_group_into_schema(
        primary_schema=release.domain_schema,
        fallback_schemas=(control,),
        app_labels=domain_apps,
    )
    ekoh_fp = migrate_app_group_into_schema(
        primary_schema=release.ekoh_schema,
        fallback_schemas=(release.domain_schema, control),
        app_labels=ekoh_apps,
        ekoh_schema_override=release.ekoh_schema,
    )
    write_canary(
        schema=release.domain_schema,
        world_id=release.world_id,
        release_id=release.id,
        schema_kind="domain",
    )
    write_canary(
        schema=release.ekoh_schema,
        world_id=release.world_id,
        release_id=release.id,
        schema_kind="ekoh",
    )
    return domain_fp, ekoh_fp


def validate_release_schemas(release) -> dict:
    domain_apps = tuple(getattr(settings, "KONNAXION_WORLD_DOMAIN_APPS", DEFAULT_DOMAIN_APPS))
    ekoh_apps = tuple(getattr(settings, "KONNAXION_WORLD_EKOH_APPS", DEFAULT_EKOH_APPS))
    domain_exists = schema_exists(release.domain_schema)
    ekoh_exists = schema_exists(release.ekoh_schema)
    checks = {
        "domain_schema_exists": domain_exists,
        "ekoh_schema_exists": ekoh_exists,
        "domain_canary": read_canary(release.domain_schema) if domain_exists else None,
        "ekoh_canary": read_canary(release.ekoh_schema) if ekoh_exists else None,
    }
    expected = {
        "world_id": release.world_id,
        "release_id": release.id,
        "contract_version": SCHEMA_CONTRACT_VERSION,
    }
    checks["domain_canary_ok"] = bool(
        checks["domain_canary"]
        and all(checks["domain_canary"].get(k) == v for k, v in expected.items())
        and checks["domain_canary"].get("schema_kind") == "domain"
    )
    checks["ekoh_canary_ok"] = bool(
        checks["ekoh_canary"]
        and all(checks["ekoh_canary"].get(k) == v for k, v in expected.items())
        and checks["ekoh_canary"].get("schema_kind") == "ekoh"
    )

    if domain_exists:
        checks["domain_migration_fingerprint"] = migration_fingerprint(
            release.domain_schema, app_labels=domain_apps
        )
        checks["domain_expected_migration_fingerprint"] = expected_migration_fingerprint(domain_apps)
        checks["domain_migrations_current"] = (
            checks["domain_migration_fingerprint"]
            == checks["domain_expected_migration_fingerprint"]
            == release.domain_migration_fingerprint
        )
        checks["domain_missing_tables"] = missing_required_tables(release.domain_schema, domain_apps)
    else:
        checks["domain_migrations_current"] = False
        checks["domain_missing_tables"] = ["<schema missing>"]

    if ekoh_exists:
        checks["ekoh_migration_fingerprint"] = migration_fingerprint(
            release.ekoh_schema, app_labels=ekoh_apps
        )
        checks["ekoh_expected_migration_fingerprint"] = expected_migration_fingerprint(ekoh_apps)
        checks["ekoh_migrations_current"] = (
            checks["ekoh_migration_fingerprint"]
            == checks["ekoh_expected_migration_fingerprint"]
            == release.ekoh_migration_fingerprint
        )
        checks["ekoh_missing_tables"] = missing_required_tables(release.ekoh_schema, ekoh_apps)
    else:
        checks["ekoh_migrations_current"] = False
        checks["ekoh_missing_tables"] = ["<schema missing>"]

    checks["domain_tables_ok"] = not checks["domain_missing_tables"]
    checks["ekoh_tables_ok"] = not checks["ekoh_missing_tables"]
    if domain_exists and ekoh_exists:
        checks["fk_isolation_violations"] = fk_isolation_violations(
            domain_schema=release.domain_schema,
            ekoh_schema=release.ekoh_schema,
            domain_apps=domain_apps,
            ekoh_apps=ekoh_apps,
        )
    else:
        checks["fk_isolation_violations"] = [{"reason": "release schema missing"}]
    checks["fk_isolation_ok"] = not checks["fk_isolation_violations"]
    checks["ok"] = all(
        checks[key]
        for key in (
            "domain_schema_exists",
            "ekoh_schema_exists",
            "domain_canary_ok",
            "ekoh_canary_ok",
            "domain_migrations_current",
            "ekoh_migrations_current",
            "domain_tables_ok",
            "ekoh_tables_ok",
            "fk_isolation_ok",
        )
    )
    return checks


def _base_tables(schema: str) -> list[str]:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT c.relname
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %s
              AND c.relkind IN ('r', 'p')
              AND NOT c.relispartition
              AND c.relname NOT IN (%s, 'django_migrations')
            ORDER BY c.relname
            """,
            [schema, CANARY_TABLE],
        )
        return [row[0] for row in cursor.fetchall()]


def _foreign_key_edges(schema: str, tables: list[str]) -> dict[str, set[str]]:
    deps: dict[str, set[str]] = {table: set() for table in tables}
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT child.relname, parent.relname
            FROM pg_constraint con
            JOIN pg_class child ON child.oid = con.conrelid
            JOIN pg_namespace child_ns ON child_ns.oid = child.relnamespace
            JOIN pg_class parent ON parent.oid = con.confrelid
            JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
            WHERE con.contype = 'f'
              AND child_ns.nspname = %s
              AND parent_ns.nspname = %s
            """,
            [schema, schema],
        )
        for child, parent in cursor.fetchall():
            if child in deps and parent in deps and child != parent:
                deps[child].add(parent)
    return deps


def _copy_order(schema: str, tables: list[str]) -> list[str]:
    deps = _foreign_key_edges(schema, tables)
    reverse: dict[str, set[str]] = defaultdict(set)
    indegree = {table: len(parents) for table, parents in deps.items()}
    for child, parents in deps.items():
        for parent in parents:
            reverse[parent].add(child)
    queue = deque(sorted(table for table, degree in indegree.items() if degree == 0))
    ordered: list[str] = []
    while queue:
        table = queue.popleft()
        ordered.append(table)
        for child in sorted(reverse.get(table, ())):
            indegree[child] -= 1
            if indegree[child] == 0:
                queue.append(child)
    if len(ordered) != len(tables):
        cycle = sorted(set(tables) - set(ordered))
        raise RuntimeError(f"World schema contains a cross-table FK cycle: {cycle}")
    return ordered


def _ensure_partition_layout(source_schema: str, target_schema: str) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT parent.relname, child.relname, pg_get_expr(child.relpartbound, child.oid)
            FROM pg_inherits i
            JOIN pg_class child ON child.oid = i.inhrelid
            JOIN pg_namespace child_ns ON child_ns.oid = child.relnamespace
            JOIN pg_class parent ON parent.oid = i.inhparent
            JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
            WHERE child_ns.nspname = %s AND parent_ns.nspname = %s
            ORDER BY parent.relname, child.relname
            """,
            [source_schema, source_schema],
        )
        parts = cursor.fetchall()
        for parent, child, bound in parts:
            # pg_get_expr returns e.g. FOR VALUES FROM (...) TO (...)
            cursor.execute(
                f"CREATE TABLE IF NOT EXISTS {_q(target_schema)}.{connection.ops.quote_name(child)} "
                f"PARTITION OF {_q(target_schema)}.{connection.ops.quote_name(parent)} {bound}"
            )


def _reset_sequences(schema: str, table: str) -> None:
    q_schema = _q(schema)
    q_table = connection.ops.quote_name(table)
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = %s AND table_name = %s
              AND (is_identity = 'YES' OR column_default LIKE 'nextval(%')
            ORDER BY ordinal_position
            """,
            [schema, table],
        )
        columns = [row[0] for row in cursor.fetchall()]
        for column in columns:
            cursor.execute("SELECT pg_get_serial_sequence(%s, %s)", [f"{schema}.{table}", column])
            seq = cursor.fetchone()[0]
            if not seq:
                continue
            q_col = connection.ops.quote_name(column)
            cursor.execute(f"SELECT MAX({q_col}) FROM {q_schema}.{q_table}")
            max_value = cursor.fetchone()[0]
            if max_value is None:
                continue
            cursor.execute("SELECT setval(%s::regclass, %s, true)", [seq, max_value])


def copy_schema_data(source_schema: str, target_schema: str) -> None:
    """Copy mutable state between schemas with FK-aware ordering.

    Target structure must already exist from canonical migrations. Partition
    layouts present in the source are materialised before parent-table inserts.
    """
    validate_schema_name(source_schema)
    validate_schema_name(target_schema)
    tables = _base_tables(source_schema)
    _ensure_partition_layout(source_schema, target_schema)
    order = _copy_order(source_schema, tables)
    with transaction.atomic():
        for table in order:
            q_table = connection.ops.quote_name(table)
            with connection.cursor() as cursor:
                cursor.execute(
                    f"INSERT INTO {_q(target_schema)}.{q_table} "
                    f"SELECT * FROM {_q(source_schema)}.{q_table}"
                )
            _reset_sequences(target_schema, table)


def clear_schema_data(schema: str) -> None:
    tables = _base_tables(schema)
    if not tables:
        return
    qualified = ", ".join(
        f"{_q(schema)}.{connection.ops.quote_name(table)}" for table in tables
    )
    with connection.cursor() as cursor:
        cursor.execute(f"TRUNCATE TABLE {qualified} RESTART IDENTITY CASCADE")


def _remap_column_values(*, schema: str, table: str, column: str, mapping: dict[int, int]) -> int:
    """Remap ids with bounded VALUES batches instead of one UPDATE per user."""
    if not mapping:
        return 0
    q_schema = _q(schema)
    q_table = connection.ops.quote_name(table)
    q_column = connection.ops.quote_name(column)
    items = list(mapping.items())
    updated = 0
    batch_size = 1_000
    with connection.cursor() as cursor:
        for offset in range(0, len(items), batch_size):
            batch = items[offset : offset + batch_size]
            placeholders = ", ".join(["(%s, %s)"] * len(batch))
            params: list[int] = []
            for old_id, new_id in batch:
                params.extend((int(old_id), int(new_id)))
            cursor.execute(
                f"WITH kx_map(old_id, new_id) AS (VALUES {placeholders}) "
                f"UPDATE {q_schema}.{q_table} AS target "
                f"SET {q_column} = kx_map.new_id "
                f"FROM kx_map WHERE target.{q_column} = kx_map.old_id",
                params,
            )
            updated += cursor.rowcount
    return updated


def remap_global_user_references(schema: str, mapping: dict[int, int]) -> int:
    """Rewrite FK/reference user ids after cloning release bridge users.

    The control-plane auth table remains global. World schema rows point at
    release-specific bridge users; cloning a release therefore requires a
    deterministic remap. Raw Smart Vote ``vote.user_id`` is also handled even
    though the legacy SQL table has no physical FK constraint.
    """
    validate_schema_name(schema)
    if not mapping:
        return 0
    updated = 0
    control = _control_schema()
    user_table = get_user_model()._meta.db_table
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT child.relname, child_col.attname
            FROM pg_constraint con
            JOIN pg_class child ON child.oid = con.conrelid
            JOIN pg_namespace child_ns ON child_ns.oid = child.relnamespace
            JOIN pg_class parent ON parent.oid = con.confrelid
            JOIN pg_namespace parent_ns ON parent_ns.oid = parent.relnamespace
            JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS ck(attnum, ord) ON TRUE
            JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS fk(attnum, ord) ON fk.ord = ck.ord
            JOIN pg_attribute child_col ON child_col.attrelid = child.oid AND child_col.attnum = ck.attnum
            WHERE con.contype = 'f'
              AND child_ns.nspname = %s
              AND parent_ns.nspname = %s
              AND parent.relname = %s
            """,
            [schema, control, user_table],
        )
        references = cursor.fetchall()

    for table, column in references:
        updated += _remap_column_values(
            schema=schema, table=table, column=column, mapping=mapping
        )

    # Smart Vote's legacy partitioned vote table models a User FK in Django
    # state but the initial physical SQL intentionally omitted that FK.
    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [f"{schema}.vote"])
        vote_exists = cursor.fetchone()[0] is not None
    if vote_exists:
        updated += _remap_column_values(
            schema=schema, table="vote", column="user_id", mapping=mapping
        )
    return updated
