# Generated by Django 5.1.9 on 2025-12-01 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonsensusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_anonymous_voting', models.BooleanField(default=False, help_text='Allow users to vote without public identity')),
                ('auto_close_votes', models.BooleanField(default=True, help_text='Automatically close votes when time expires')),
                ('quorum_percentage', models.DecimalField(decimal_places=2, default=33.0, help_text='Minimum participation % required for a vote to be valid', max_digits=5)),
                ('passing_threshold', models.DecimalField(decimal_places=2, default=51.0, help_text="Percentage of 'Yes' votes needed to pass", max_digits=5)),
                ('default_voting_duration_days', models.PositiveIntegerField(default=7, help_text='Default duration for new votes in days')),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='Store additional dynamic settings here (e.g. UI themes, experimental flags)')),
            ],
            options={
                'verbose_name': 'Konsensus Configuration',
                'verbose_name_plural': 'Konsensus Configurations',
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='moderationticket',
            options={'ordering': ['-severity', '-created_at'], 'verbose_name': 'Moderation Ticket', 'verbose_name_plural': 'Moderation Tickets'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='moderationticket',
            name='created',
        ),
        migrations.RemoveField(
            model_name='moderationticket',
            name='modified',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moderationticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
