# FILE: backend/konnaxion/users/migrations/0003_remove_user_avatar_user_profile_artwork.py
# Generated by Django 5.1.9 on 2025-11-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kreative', '0002_archivedocument_culturalpartner_digitalarchive_and_more'),
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_using_as_profile', to='kreative.kreativeartwork'),
        ),
    ]
