# Generated by Django 5.1.9 on 2025-12-01 22:15

import konnaxion.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_avatar_user_profile_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User-uploaded avatar image.', null=True, upload_to=konnaxion.users.models.user_avatar_upload_to),
        ),
    ]
