# Generated by Django 5.1.9 on 2025-12-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('human', 'Human'), ('service', 'Service')], default='human', help_text='Categorises the account: human or internal service.', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ethikos_elite',
            field=models.BooleanField(default=False, help_text='If true, this account is allowed to write (stances/arguments) in Ethikos debates. Klones and staff may also participate via can_participate_in_ethikos.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_klone',
            field=models.BooleanField(default=False, help_text="If true, this human account represents a synthetic 'klone' persona rather than a self-controlled user."),
        ),
    ]
