# FILE: backend/konnaxion/konnected/migrations/0003_offlinepackage_bundle_path_offlinepackage_created_by_and_more.py
# Generated by Django 5.1.9 on 2025-11-26 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnected', '0002_offline_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepackage',
            name='bundle_path',
            field=models.CharField(blank=True, help_text='Filesystem path to the last generated manifest, if any.', max_length=500),
        ),
        migrations.AddField(
            model_name='offlinepackage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this offline package definition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinepackage',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='Resources currently included in this offline package.', related_name='offline_packages', to='konnected.knowledgeresource'),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='auto_sync',
            field=models.BooleanField(default=False, help_text='If true, include in scheduled offline build jobs.'),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='build_progress_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current build progress (0–100).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='include_types',
            field=models.JSONField(blank=True, help_text='Optional list of content types to include (article, video, lesson, quiz, dataset).', null=True),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='item_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of resources included in the last built bundle.'),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='language_filter',
            field=models.CharField(blank=True, help_text="Optional language filter (e.g. 'en', 'fr').", max_length=32),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='last_built_at',
            field=models.DateTimeField(blank=True, help_text='When this package was last fully built.', null=True),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='last_error_message',
            field=models.TextField(blank=True, help_text='Last build error, if the package is in a failed state.'),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='level_filter',
            field=models.CharField(blank=True, help_text='Optional difficulty/level filter.', max_length=255),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='max_size_mb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional upper bound for package size in MB.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='target_device_type',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop / desktop'), ('tablet', 'Tablet'), ('usb', 'USB / external media'), ('other', 'Other / mixed devices')], help_text='Intended primary device type, if any.', max_length=16),
        ),
        migrations.AlterField(
            model_name='offlinepackage',
            name='total_size_mb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Approximate total bundle size in megabytes.', max_digits=10),
        ),
    ]
