# Generated by Django 5.1.9 on 2025-12-01 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnected', '0003_offlinepackage_bundle_path_offlinepackage_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, help_text='Optional public display name; falls back to user if blank.', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Short biography shown on the mentorship page.')),
                ('expertise_areas', models.JSONField(blank=True, help_text="List of expertise/subject tags (e.g. ['Math', 'Physics']).", null=True)),
                ('languages', models.JSONField(blank=True, help_text="List of language names or codes (e.g. ['English', 'French']).", null=True)),
                ('level', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('adult', 'Adult / educator')], help_text='Primary learner level this mentor supports.', max_length=16)),
                ('focus_areas', models.JSONField(blank=True, help_text='Optional list of focus areas for mentoring.', null=True)),
                ('max_mentees', models.PositiveIntegerField(blank=True, help_text='Optional cap on active mentees this mentor will take.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether the mentor appears in discovery lists.')),
                ('is_accepting_mentees', models.BooleanField(default=True, help_text='Quick toggle for whether new requests are allowed.')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Optional average feedback rating (e.g. 4.8).', max_digits=3, null=True)),
                ('sessions_completed', models.PositiveIntegerField(default=0, help_text='Approximate count of completed mentorship sessions.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('learning_goal', models.TextField(help_text="Learner's main goal or topic for mentorship.")),
                ('preferred_language', models.CharField(blank=True, help_text='Optional preferred language for sessions.', max_length=64)),
                ('age_group', models.CharField(blank=True, help_text="Optional age group descriptor (e.g. '12–14').", max_length=64)),
                ('contact_channel', models.CharField(blank=True, help_text='Preferred communication channel (e.g. email, chat, video).', max_length=64)),
                ('additional_notes', models.TextField(blank=True, help_text='Any extra context the learner wants to share.')),
                ('responded_at', models.DateTimeField(blank=True, help_text='Timestamp when the mentor accepted/declined the request.', null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='konnected.mentorprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
