# FILE: backend/konnaxion/trust/migrations/0001_initial.py
# Generated by Django 5.1.9 on 2025-11-24 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short title, e.g. 'MSc Climate Policy'.", max_length=255)),
                ('issuer', models.CharField(blank=True, help_text='Issuing institution or body.', max_length=255)),
                ('issued_at', models.DateTimeField(blank=True, help_text='When the credential was issued (if known).', null=True)),
                ('file', models.FileField(blank=True, help_text='Binary document attached to this credential.', null=True, upload_to='trust/credentials/%Y/%m/%d')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', help_text='Review status in the trust workflow.', max_length=16)),
                ('notes', models.TextField(blank=True, help_text='Optional reviewer notes shown read‑only in the UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who submitted this credential.', on_delete=django.db.models.deletion.CASCADE, related_name='trust_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='trust_crede_user_id_3fc81d_idx')],
            },
        ),
    ]
