# Generated by Django 5.1.9 on 2025-12-01 22:15

import konnaxion.trust.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='file',
            field=models.FileField(blank=True, help_text='Binary document attached to this credential.', null=True, upload_to=konnaxion.trust.models.credential_upload_to),
        ),
        migrations.AlterField(
            model_name='credential',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional reviewer notes shown read-only in the UI.'),
        ),
    ]
